---
title: "Raster Processing in R"
author: "Adam Smith"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    theme: united
    highlight: textmate
    css: ../custom.css
---


## Load required R packages

```{r load_packages}
library(raster)
library(rgdal)
library(rasterVis)
```

## Get some data to play with

We'll start with two example raster processing applications.  One is contrived for the purposes of this module and the second is a recent application on a National Wildlife Refuge.

```{r get_data}
# NCTC DEM
dem <- raster('./Data/dem.img')
dem

# NCTC color orthophoto
GDALinfo('./Data/NAIP_CIR_NE.tif')
GDALinfo('./Data/NAIP_CIR_NW.tif')
cir_NE <- raster('./Data/NAIP_CIR_NE.tif')
cir_NE # NOPE, only loaded first band
cir_NE <- brick('./Data/NAIP_CIR_NE.tif')
cir_NE
cir_NW <- brick('./Data/NAIP_CIR_NW.tif')

plot(cir_NE)                  # plot all bands (if > 1) in separate panels
plot(cir_NE[[1]])             # plot first band only
plot(cir_NW[[1]], add = TRUE) # plot first band only, add to existing plot

# Lake Mattamuskeet NAIP 2014 color-infrared imagery 
# Originally 1-m resolution; resampled to 9 m resolution
LM <- brick("./Data/LM_9m.tif")
```

```{r Jamaica}

calc_NDWI <- function(cir_raster) {
  green <- cir_raster[[2]]
  nir <- cir_raster[[4]]
  NDWI <- (green - nir) / (green + nir)
  NDWI
}


plot(jam) # Admin boundary
plot(dem) # Elevation data
levelplot(dem)
levelplot(precip)
plot(jam, add = TRUE)

pal <- colorNumeric(terrain.colors(32), values(dem),
                    na.color = "transparent")
leaflet() %>% addTiles() %>% addRasterImage(dem, colors = pal, opacity = 0.5) %>%
  addLegend(pal = pal, values = values(dem), title = "Elevation (m)")
```




```{r Lake_Mat}
plot(LM)
plotRGB(LM, r=1, g=2, b=3)
```