





----

<div id="handson" markdown="1">
<h2> Hands On: Import Line and Point Shapefiles</h2>

Using the steps above, import:
- West Virginia land cover raster *layer* (WV_habitat.img)
- NAIP color infrared photos as a raster *brick* 
- NCTC boundary (nctc_boundary) shapefile
- plot the `R`. Call the Harv_roads object `lines_HARV` and the HARVtower_UTM18N
`point_HARV`.

Answer the following questions:

1. What type of `R` spatial object is created when you import each layer?
2. What is the `CRS` and `extent`for each object?
3. Do the files contain, points, lines or polygons?
4. How many spatial objects are in each file?
</div>


## Hands On #? Solution
```{r import-point-line, eval=FALSE, results="hide" }
# import line shapefile
lines_HARV <- readOGR("NEON-DS-Site-Layout-Files/HARV",layer = "HARV_roads")
# import point shapefile
point_HARV <- readOGR("NEON-DS-Site-Layout-Files/HARV", layer="HARVtower_UTM18N")

# 1
class (lines_HARV)
class (point_HARV)

# 2
crs(lines_HARV)
extent(lines_HARV)
crs(point_HARV)
extent(point_HARV)

# 3 
#lines_HARV contains only lines and point_HARV contains only 1 point

# 4 -> numerous ways to find this; lines_HARV=13,
length(lines_HARV)  #easiest, but not previously taught
lines_HARV  #look at 'features'
attributes(lines_HARV)  #found in the $data section as above

# Alternative code for 1-4: view metadata/attributes all at once
lines_HARV
attributes(lines_HARV)

```

## CRS
The Coordinate Reference System (CRS) of spatial objects defines where they are placed on the Earth’s
surface. You may have noticed ’proj4string ’in the summary of lnd above: the information that follows
represents its CRS. Spatial data should always have a CRS. If no CRS information is provided, and the
correct CRS is known, it can be set as follow:
proj4string(lnd) <- NA_character_ # remove CRS information from lnd
proj4string(lnd) <- CRS("+init=epsg:27700") # assign a new CRS
R issues a warning when the CRS is changed. This is so the user knows that they are simply changing the
CRS, not reprojecting the data. An easy way to refer to different projections is via EPSG codes.
Under this system 27700 represents the British National Grid. ‘WGS84’ (epsg:4326) is a very commonly
used CRS worldwide. The following code shows how to search the list of available EPSG codes and create a
new version of lnd in WGS84:3
EPSG <- make_EPSG() # create data frame of available EPSG codes
EPSG[grepl("WGS 84$", EPSG$note), ] # search for WGS 84 code
## code note prj4
## 249 4326 # WGS 84 +proj=longlat +datum=WGS84 +no_defs
lnd84 <- spTransform(lnd, CRS("+init=epsg:4326")) # reproject


## Why R for spatial analysis?

- R is free and open source
- Packages
- Active community: > 2 million users worldwide
- Explore your data in all its dimensions
- Integrated analysis chain from download to analysis
- Implement complex and custom made algorithms and functions
- Automation
- Make work reproducible
    - promotes collaboration
    - informs your future self
