
## Import Data Tables

- *easiest* import format is plain text, especially CSV (`read.table` or `read.csv`)
    - R imports as a `data.frame` by default
- many other options
    - R's native structure (see `?save`)
    - databases (MySQL, SQLite, Access)
    - Excel, SAS, SPSS, DBF, etc.

## Example CSV import

```{r}
download.file(url = "http://tinyurl.com/testCSV", destfile = "./data/test.csv")
test <- read.table("./data/test.csv", header = TRUE, sep = ",")
test <- read.csv("./data/test.csv", header = TRUE)
class(test)
glimpse(test)
```

```{r eval=FALSE, include=FALSE}
# convert .Rmd script to .R file for instruction
# note .R file subsequently cleaned up for code margin of ~80 char

rmd2rscript <- function(infile,outfile){
  # read the file
  flIn <- readLines(infile)
  # identify the start of code blocks
  cdStrt <- which(grepl(flIn, pattern = "```{r*", perl = TRUE))
  # identify the end of code blocks
  cdEnd <- sapply(cdStrt, function(x){
    preidx <- which(grepl(flIn[-(1:x)], pattern = "```", perl = TRUE))[1]
    return(preidx + x)
  })
  # define an expansion function
  # strip code block indacators
  flIn[c(cdStrt, cdEnd)] <- ""
  expFun <- function(strt, End){
    strt <- strt+1
    End <- End-1
    return(strt:End)
  }
  idx <- unlist(mapply(FUN = expFun, strt = cdStrt, End = cdEnd, 
                SIMPLIFY = FALSE))
  # add comments to all lines except code blocks
  comIdx <- 1:length(flIn)
  comIdx <- comIdx[-idx]
  for(i in comIdx){
    flIn[i] <- paste("# ", flIn[i], sep = "")
  }
  # create an output file
  #nm <- strsplit(infile, split = "\\.")[[1]][1]
  flOut <- file(outfile, "w")
  for(i in 1:length(flIn)){
    cat(flIn[i], "\n", file = flOut, sep = "\t")
  }
  close(flOut)
}

infile <- 'Raster_workshop_pres.Rmd'
outfile <- 'R/GTW_raster.R'

rmd2rscript(infile, outfile)
```